"""Find candidate vendor pages, then fan out one extraction branch per candidate.

Queries are built from templates rather than generated by a model. Templates are
free, deterministic, and easy to reason about when results are poor — and on a
1,000-credit/month search budget, spending LLM tokens to write a search string
we can compose ourselves is not a good trade.
"""

from __future__ import annotations

import asyncio
import logging
from urllib.parse import urlsplit

from langchain_core.runnables import RunnableConfig
from langgraph.types import Send

from procurement_agent.config import get_settings
from procurement_agent.crawl.fetcher import get_fetcher
from procurement_agent.designations import is_grade_specific
from procurement_agent.graph.context import run_budget
from procurement_agent.graph.state import (
    MaterialResearch,
    MaterialSpec,
    SessionState,
    VendorCandidate,
)
from procurement_agent.search.client import BudgetExhausted, SessionBudget, extract, search
from searchroute import Depth

log = logging.getLogger(__name__)

#: Directory and marketplace hosts that aggregate suppliers. Useful for recall,
#: but ranked below real manufacturers later.
DIRECTORY_HINTS = ("thomasnet.com", "matmatch.com", "alibaba.com", "indiamart.com")

MAX_QUERIES = 6

#: Cap on candidates carried into extraction. Each one costs a page fetch and a
#: model call, so this is the main lever on both search credits and runtime.
MAX_CANDIDATES = 12

#: Below this many characters, inline content is not worth extracting contacts
#: from and a real fetch is worth its cost.
MIN_USEFUL_CONTENT = 400


def build_queries(
    spec: MaterialSpec,
    research: MaterialResearch | None,
    sourcing_companies: list[str] | None = None,
) -> list[str]:
    """Distinct angles on the same material, deduplicated and capped.

    Several narrow queries beat one broad one: "supplier", "distributor" and
    "manufacturer" surface genuinely different companies, and searching the
    formal designation finds vendors who never use the trade name.

    Companies named in research papers go FIRST. A paper stating a material was
    supplied by a named company is far stronger evidence than a search ranking,
    so those queries should not be the ones dropped when the cap bites.
    """
    label = spec.search_label()
    queries: list[str] = []

    # Highest-confidence first: someone documented buying this material there.
    for company in (sourcing_companies or [])[:3]:
        queries.append(f"{company} {spec.material_name} contact")

    for intent in ("supplier", "distributor", "manufacturer"):
        queries.append(f"{label} {intent}")

    # Only grade-specific terms become queries. `material_research` already
    # verifies these against retrieved sources, so this is the second guard
    # rather than the first: it catches a family standard like "ASTM B348",
    # which can be genuinely present in the sources and still match every
    # titanium bar grade ever made rather than the one being bought.
    names: list[str] = []
    if research:
        names += [d for d in research.designations if d and is_grade_specific(d)][:2]
        names += [s for s in research.synonyms if s and is_grade_specific(s)][:1]
    for name in names:
        queries.append(f"{name} supplier stockist")

    queries.append(f"{label} suppliers site:thomasnet.com")

    seen: set[str] = set()
    unique: list[str] = []
    for query in queries:
        key = query.casefold()
        if key not in seen:
            seen.add(key)
            unique.append(query)
    return unique[:MAX_QUERIES]


def _domain(url: str) -> str:
    host = urlsplit(url).netloc.casefold()
    return host[4:] if host.startswith("www.") else host


def _company_from(result) -> str:
    """Best-effort company name: the title up to its first separator."""
    title = result.title.strip()
    for sep in (" | ", " - ", " – ", " — ", ": "):
        if sep in title:
            title = title.split(sep)[0].strip()
            break
    return title or _domain(result.url)


async def vendor_search(state: SessionState, config: RunnableConfig = None) -> dict:
    """Run the query set, deduplicate by domain, and record what we found."""
    spec = state.get("material_spec")
    if spec is None:
        raise ValueError("vendor_search ran before a spec was available")

    settings = get_settings()
    # The run's own budget, not a slice of it: every other searching node takes
    # a named allocation first, so whatever is left is deliberately this node's
    # to spend. Finding vendors is what the run exists to do.
    budget = run_budget(config, settings)
    sourcing_companies = state.get("sourcing_companies", [])
    queries = build_queries(spec, state.get("research"), sourcing_companies)

    async def run(query: str) -> tuple[str, list]:
        try:
            # CONTENT depth with hydration: providers that return page text
            # inline save a separate extract call, and extraction is the more
            # expensive half of the budget.
            return query, await search(
                query,
                budget,
                depth=Depth.CONTENT,
                max_results=settings.results_per_query,
                max_hydrate=settings.results_per_query,
            )
        except BudgetExhausted:
            log.info("vendor_search: budget exhausted before %r", query)
            return query, []

    # Bounded concurrency: free-tier rate limits, not latency, are the constraint.
    semaphore = asyncio.Semaphore(settings.max_fanout)

    async def guarded(query: str) -> tuple[str, list]:
        async with semaphore:
            return await run(query)

    gathered = await asyncio.gather(*(guarded(q) for q in queries))

    # A query counts as research-derived when it was built from a company a
    # paper named, so hits from it inherit that provenance.
    research_queries = {
        f"{c} {spec.material_name} contact".casefold() for c in sourcing_companies
    }

    # Keep the first hit per domain: several pages from one vendor add no leads.
    by_domain: dict[str, VendorCandidate] = {}
    for query, results in gathered:
        for result in results:
            domain = _domain(result.url)
            if not domain or domain in by_domain:
                continue
            # SearchRoute's result types are slotted dataclasses, not Pydantic,
            # so they are projected into VendorCandidate here rather than
            # carried into state - a checkpoint has to be serialisable.
            by_domain[domain] = VendorCandidate(
                company_name=_company_from(result),
                url=result.url,
                snippet=result.snippet or "",
                raw_content=result.content,
                query=query,
                from_research=query.casefold() in research_queries,
            )

    candidates = list(by_domain.values())[:MAX_CANDIDATES]

    # Fill in page text for candidates whose inline content was too thin.
    # Deliberately after deduplication and the cap, so credits are only spent
    # on pages that will actually reach contact extraction — without this,
    # almost every lead comes back with "page content could not be retrieved".
    await _fill_content(budget, candidates)

    with_content = sum(1 for c in candidates if c.raw_content)
    log.info(
        "vendor_search: %d queries -> %d unique domains -> %d kept, "
        "%d with page content, %d credits left",
        len(queries),
        len(by_domain),
        len(candidates),
        with_content,
        budget.credits_remaining,
    )

    return {
        "search_queries": queries,
        "vendor_candidates": candidates,
        "search_credits_remaining": budget.credits_remaining,
        "truncated": state.get("truncated", False) or budget.truncated,
        "status": "researching",
    }


async def _fill_content(budget: SessionBudget, candidates: list[VendorCandidate]) -> None:
    """Fetch page text for candidates the search returned only a snippet for.

    Two tiers, cheapest first. crawl4ai is a local headless browser: it costs no
    credits and, unlike SearchRoute's extraction providers, it renders
    JavaScript - which matters because vendor contact details frequently sit in
    a nav or footer that only exists after render. Only what it cannot retrieve
    falls through to a metered extract.

    Mutates `candidates` in place. Failures are swallowed: a candidate with no
    page text still ships as a lead carrying its source URL, which is more
    useful than dropping a real company because one fetch failed.
    """
    needing = [
        c for c in candidates
        if not c.raw_content or len(c.raw_content) < MIN_USEFUL_CONTENT
    ]
    if not needing:
        return

    needing = await _crawl_free(budget, needing)
    if not needing:
        return

    filled = await extract([c.url for c in needing], budget)
    for candidate in needing:
        content = filled.get(candidate.url)
        if content and len(content) > len(candidate.raw_content or ""):
            candidate.raw_content = content


async def _crawl_free(
    budget: SessionBudget, needing: list[VendorCandidate]
) -> list[VendorCandidate]:
    """Fetch with crawl4ai, returning only what still needs a metered extract.

    Best-effort by construction: any page the crawler cannot get simply stays in
    the returned list and falls through to the paid tier.
    """
    fetcher = get_fetcher(get_settings())
    if not fetcher.is_enabled():
        return needing

    pages = await fetcher.fetch_many([c.url for c in needing])
    by_url = {p.url: p for p in pages if p.is_useful}

    still_needing: list[VendorCandidate] = []
    for candidate in needing:
        page = by_url.get(candidate.url)
        if page and len(page.content) > len(candidate.raw_content or ""):
            candidate.raw_content = page.content
            budget.crawled_free += 1
        else:
            still_needing.append(candidate)

    log.info(
        "crawl4ai: %d/%d pages fetched free, %d falling through to paid extract",
        len(needing) - len(still_needing),
        len(needing),
        len(still_needing),
    )
    return still_needing


def fan_out_to_extraction(state: SessionState) -> list[Send] | str:
    """One extraction branch per candidate.

    Concurrency is capped by `max_concurrency` on the run config rather than
    here, so the cap applies across the whole graph rather than per node.
    """
    candidates = state.get("vendor_candidates", [])
    if not candidates:
        log.warning("fan_out_to_extraction: no candidates, skipping to summary")
        return "vendor_summary"
    return [
        Send(
            "contact_extraction",
            {
                "candidate": c,
                "material_spec": state.get("material_spec"),
                # Forwarded so certification filtering knows which standards
                # actually belong to this material.
                "research": state.get("research"),
            },
        )
        for c in candidates
    ]
